version: "3.1"  
services:
  weather-save-data:
    container_name: save
    image: trevorchew/weather:latest
    user: root
    volumes:
      - weather:/var/opt/mssql/data
    profiles: ["database", "all"]
volumes:
  weather:
    external: true