version: "3.1"  
services:

  weather-unit-test:
    container_name: test
    profiles: ["seed", "all"]
    volumes:
      - weather:/data/test
    build: weather-unit-test/ApiService.Tests

  weather-pull-data:
    container_name: pull
    profiles: ["seed", "all"]
    environment:
      TZ: "Asia/Singapore"
    build: weather-pull-data
    volumes:
      - weather:/data/pull
    depends_on:
      - weather-unit-test

  weather-push-data:
    container_name: push
    profiles: ["seed", "all"]
    environment:
      - CONNECTION_STRING
    build: weather-push-data
    volumes:
      - weather:/data/push
    depends_on:
      - weather-save-data
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 60s
    secrets:
      - my-secret
  
  weather-save-data:
    container_name: save
    image: trevorchew/weather:latest
    user: root
    volumes:
      - weather:/var/opt/mssql/data
    profiles: ["database", "all"]

secrets:
  my-secret:
    file: secret.json
volumes:
  weather:
    external: true