version: "3.1"  
services:
  weather-unit-test:
    container_name: weather-unit-test
    volumes:
      - volume:/data/test
    build: weather-unit-test/ApiService.Tests

  weather-save-data:
    container_name: weather-save-data
    image: mcr.microsoft.com/mssql/server:2019-CU18-ubuntu-20.04
    user: root
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Passw0rd#"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - volume:/var/opt/mssql/data
    
  weather-pull-data:
    container_name: weather-pull-data
    environment:
      TZ: "Asia/Singapore"
    build: weather-pull-data
    volumes:
      - volume:/data/pull
    depends_on:
      - weather-unit-test

  weather-push-data:
    container_name: weather-push-data
    build: weather-push-data
    volumes:
      - volume:/data/push
    depends_on:
      - weather-save-data
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 60s
    secrets:
      - my-secret

secrets:
  my-secret:
    file: secret.json
volumes:
  volume: